version: '3.8'
services:
  meilisearch:
    image: getmeili/meilisearch:v1.5
    container_name: meilisearch
    ports:
      - '7700:7700'
    environment:
      MEILI_NO_ANALYTICS: 'true'
      # Set a strong master key in production
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-masterKey}
    volumes:
      - meili_data:/data.ms

volumes:
  meili_data:
